public class SalesforceDeveloper {
    public void myFirstCode(){
        System.debug('Favori Şehrim Kocaeli');
        System.debug('Favori Film Forrest Gump');
        System.debug('Favori Mevsim İlkbahar');
    }
    public void myFavorites(){
        String city = 'Manisa';
        System.debug('Bulunduğum şehir ' + city);
        Integer favNum = 85;
        System.debug('Favori numaram ' + favNum);
        System.debug('Bulunduğum şehir -> ' + city + ' Favori numaram -> ' + favNum);
    }
}
