IfAndForLoop11 ifl1 = new IfAndForLoop11();
ifl1.ifBreadSwitch('ekmek', 3);
ifl1.ifBreadSwitch('simit', 2);
ifl1.ifBreadSwitch('çay', 3);
ifl1.ifBreadSwitch('tea', 3);


ifl1.ifBread('ekmek', 2);
ifl1.ifBread('simit', 1);
ifl1.ifBread('kek', 2);
ifl1.ifBread('pogaca', 3);


ifl1.ifNumbers(13, 8);
ifl1.ifNumbers(13, 40);
ifl1.ifNumbers(11, 11);

IfAndForLoop11 ifl3 = new IfAndForLoop11();
ifl3.forLoopSumNumbers(11);

