public class ogrenci11 {
    public ogrenci11() {
        System.debug('Yeni bir kayıt yapıldı');
    }

    public string firstName;
    public string lastName;
    private string schoolName = 'Dream School';
    public string className;
    public string language;
    public Boolean art;
    public Boolean sport;
    public Integer ingGrade;
    public integer mathGrade;
    public integer fenGrade;  
}
